---
title: "MyRtools"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MyRtools}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, warning=F}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### R envirnment and version of packages 
```{r}
library(MyRtools)
print(sessionInfo())

RUN <- F
```

### visualization
```{r}
if(RUN){
  # 1 scatterplot
  scatterplot1()
  
  # 2 histogram
  histogram1()
  
  # 3 Bar chart and bar chart
  bar2()
  
  # 4 boxplot 
  boxplot1()
  
  # 5 area plot
  area1()
  
  # 6 heatmap
  heat1()
  
  # 7 correlate
  corrplot1()
  
  # 8 line chart
  linechart1()
  
  # 9 venn chart
  venn2()
  
  # 10 volcano 
  volcano1()
  
  # 11 pie chart
  pie1()
}
```

### Statistic Methods  
```{r}
if(RUN){
  # nonparamteric test
  result1 <- wilcox_rank(phen, prof, "SampleID", "Stage", "BASE", "WASH")
  result2 <- wilcox_sign(phen, prof, "SampleID", "ID", "Stage", "BASE", "WASH")
  result3 <- kruskal_test(phen, prof, "SampleID", "Stage")
  result4 <- friedman_test(phen, prof, "SampleID", "ID", "Stage")

  # paramteric test
  res1 <- unpaired_ttest(phen, prof, "SampleID", "Stage", "BASE", "WASH")
  res2 <- paired_ttest(phen, prof, "SampleID", "ID", "Stage", "BASE", "WASH")
  res3 <- ANOVA_one(phen, prof, "SampleID", "Stage")
  res4 <- ANOVA_two(phen, prof, "SampleID", "Stage", "Group")
}
```

### application on visualization
```{r}
if(RUN){
  pca_plot <- PCA_scatterplot(pca_site)
  per_res <- PERMANOVA(phen, prof)
}
```

